name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm add @unlighthouse/cli puppeteer

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site https://wework.co.in --budget 75 --build-static

      - name: Deploy report to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './.unlighthouse'
          production-branch: main
          production-deploy: true
          github-token: "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"
          deploy-message: "New Release Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: "kvwAC1KaIiEpvpthb7t5D-kMKW1JLxB6gGLPe-Mc_aY"
          NETLIFY_SITE_ID: "a3a06b11-a7d4-4e54-bd43-ecf7a9a6dc47"
        timeout-minutes: 1
